name: Trivy Analysis

permissions:
  contents: read
  actions: read
  security-events: write

on:
  pull_request:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 1 */3 *'

env:
  SARIF_FILE: 'trivy-results.sarif'

jobs:
  build:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run Trivy vulnerability scanner on the cloned repository files
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          version: 'v0.68.2'
          scan-type: 'fs'
          scanners: 'vuln,misconfig,secret,license'
          ignore-unfixed: true
          format: 'sarif'
          output: ${{ env.SARIF_FILE }}
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

      - name: Check Trivy scan results existence
        run: |
          if [ ! -f "${{ env.SARIF_FILE }}" ]; then
            echo "Error: ${{ env.SARIF_FILE }} does not exist."
            exit 1
          fi
          ls -lash ${{ env.SARIF_FILE }}
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
        with:
          sarif_file: ${{ env.SARIF_FILE }}



